# Generated by Django 4.0.4 on 2022-06-20 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blockapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeighbourHood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('neighbourhood_logo', models.ImageField(upload_to='post_img/')),
                ('health_department', models.CharField(blank=True, max_length=15, null=True)),
                ('police_department', models.CharField(blank=True, max_length=15, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('neighbourhood_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='neighbourhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blockapp.neighbourhood'),
        ),
        migrations.AddField(
            model_name='post',
            name='neighbourhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blockapp.neighbourhood'),
        ),
    ]
