# Generated by Django 4.0.4 on 2022-06-23 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blockapp', '0004_neighbourhood_occupants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('1', 'Crimes'), ('2', 'Health'), ('3', 'Nyumba Kumi meetups'), ('4', 'Fire Breakouts'), ('5', 'Lost and Found'), ('6', 'Death'), ('7', 'Event')], max_length=255),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, max_length=255, null=True, upload_to='avatar/')),
                ('title', models.CharField(max_length=255, null=True)),
                ('bio', models.TextField(blank=True, default='')),
                ('neighbourhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blockapp.neighbourhood')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
